### ISSUE TITLE
Adjust Lead Score by Membership Site engagement

### ISSUE THREAD

**Issue by stephenhutson** [Simplero/Roadmap#177] opened 2017-11-02 22:55 UTC
We would like to adjust lead score based on how active a contact has been, meaning how many pages within a membership site they have views, courses completed, resources downloaded, number of Forum comments, etc. The ultimate goal is to setup automation based on activity vs inactivity.

**Comment by calvincorreli** [comment] 2017-12-06 21:12
I'm going to close this as a duplicate of the other one about automations based on engagement.

**Closed by calvincorreli** 2017-12-06 21:12 UTC
