### ISSUE TITLE
Quiz minimum of 80% pass to move on to next module. 

### ISSUE THREAD

**Issue by Dancekidscanada** [Simplero/Roadmap#494] opened 2019-04-03 09:06 UTC
Can Quizzes have a minimum requirement of 80% pass rate to move on to next module?

**Comment by calvincorreli** [comment] 2019-04-10 17:37
Closed as duplicate of https://github.com/Simplero/Roadmap/issues/447

**Closed by calvincorreli** 2019-04-10 17:37 UTC
