### ISSUE TITLE
Reuse courses across membership sites

### ISSUE THREAD

**Issue by infospray** [Simplero/Roadmap#185] opened 2017-11-14 12:43 UTC
Maybe it's because I'm using the new membership sites/courses wrong.

However, I have created 3 membership sites (one for recordings of my live events, one for my online courses and a special one for my mentor program). 

However now I want to give my the students with access to my mentor program some bonus courses that are currently in the other membership site.

I don't want to duplicate all the content (the entire course), so it would be great if you could somehow add a reference to a course that is in another membership site.

**Comment by calvincorreli** [comment] 2018-04-25 00:28
Sounds like a duplicate of https://github.com/Simplero/Roadmap/issues/161

**Closed by calvincorreli** 2018-04-25 00:28 UTC
Labels: shortlist

**Comment by infospray** [comment] 2018-04-26 07:01
Hmm, I'm not sure I think it's the same as #161 

I want to use a course from one membership site in another.

Sure I could make a full copy/clone of the course, but then I would have to update content in two places whenever I change something. 

My issue is that I have two membership sites, and I want to use courses in one of them, as bonuses in the other one.

**Comment by calvincorreli** [comment] 2018-04-26 11:30
That's exactly what I see that #161 says. If we move courses to the main content menu, that would imply that they're a thing in themselves, outside of sites, and you can sort-of "mount" them inside the sites. Isn't that exactly what you're looking for?

**Comment by mortenspindler** [comment] 2018-04-26 12:10
Ah, now I understand. Yea, that would be, what we are looking for, dunno about Rasmus

**Comment by infospray** [comment] 2018-05-08 12:06
Yes, that would work in my case (having a m:n relationship between membership sites and courses, instead of an 1:m).
