### ISSUE TITLE
Contact Form Functionality

### ISSUE THREAD

**Issue by barten97** [Simplero/Roadmap#137] opened 2017-10-11 02:07 UTC
Hello, it would be great if the system offered a proper contact form. 
We have added an embedded form but when someone leaves a message there is no alert on the system to let know a message is waiting. 
http://www.theanatomyschool.com/pages/contact

**Comment by calvincorreli** [comment] 2017-12-06 23:14
Duplicate of #33

**Closed by calvincorreli** 2017-12-06 23:14 UTC
